source 'https://rubygems.org'

ruby '2.6.5'
gem 'sinatra', '>=1.0'
gem 'sinatra-contrib'
gem 'rake'
gem 'datamapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'pry'
